config/routes.rb
Rails.application.routes.draw do
  
  resources :about, only: :index
  #resources :users_comments_moderator, only: :index
  resources :commentary, only: :index
  
  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commentary.rb
class Commentary < ApplicationRecord
	validates :body, nill: false
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :commentaries
	belongs_to :user
	validates :title, nill: false
	validates :body, nill: false
  #has_many :user
  #has_many :rating
  #belongs_to :rating
  #has_one :rating and has_one :user
end

app/models/rating.rb
class Rating < ApplicationRecord
	validates :value, :inclusion => 1..5
  	belongs_to :user
  	belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord

	has_many :commentaries
  has_many :posts, dependent: :nullify

  validates :name, presence: true
  #validates :name, length: { maximum: 16, minimum: 2 }
  validates :name, uniqueness: true
  #validates :name, format: { with: /\A\w+\z/i, message: ': допускаются только буквы и цифры' }

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/commentary_controller.rb
class CommentaryController < ApplicationController
	def index
		@commentaries = Commentary.all
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/users_comments_moderator_controller.rb
class UsersCommentsModeratorController < ApplicationController

	#before_action :set_post, only: [:index]

	def index
		@users_coment = Commentaries.body
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commentary_helper.rb
module CommentaryHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/commentary/index.html.erb
<h3>Ну да криво косо, но как получилось)))И так еле сделал)))</h3><br>
<% @commentaries.find_each do |coment| %>
	
	<% if coment.user.moderator == true %>
		<h4>Author '<%= coment.user.name.capitalize %>' is a moderator <%= coment.user.moderator %></h4>
		<p><%= coment.body.delete '[""]' %></p>
		<br>
	<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<a href="<%= root_path %>">index</a>
  		<a href="<%= about_index_path %>">About me</a>
      <a href="<%= commentary_index_path %>">Commentary is a moderator</a>
    <%= yield %>
    	<h2>Footer</h2>
	</div>
  </body>
</html>

app/views/users_comments_moderator/index.html.erb
<h1>Post</h1>

<tbody>
      <tr>
        <h1>Header</h1>
        <td><%= @users_coment%></td>
      </tr>
      <br>
  </tbody>